### PR TITLE
Give the data attribute an actual type (object)

### LINKED ISSUE #119: What should be the data type for the response?
What should be the WebIDL data type for the [`DigitalCredential.data`](https://wicg.github.io/digital-credentials/#the-digitalcredential-interface) response?

This is currently returning `any` (to [keep](https://github.com/WICG/digital-credentials/pull/107) Safari and Chrome's implementation interoperable), but we should probably be more specific than that.

A few options that occurred to us:

* An `Uint8Array`
* A `DOMString` ([what WebOTP uses](https://wicg.github.io/web-otp/#OTPCredential))
* An `USVString` ([what FedCM uses](https://fedidcg.github.io/FedCM/#browser-api-identity-credential-interface) -- as opposed to a `DOMString` it can take UTF-8, e.g. `application/json`, guidance from TAG [here](https://github.com/whatwg/webidl/issues/84) and [here](https://w3ctag.github.io/design-principles/#idl-string-types)),
* An `ArrayBuffer` ([what WebAuthn is using](https://w3c.github.io/webauthn/#authenticatorresponse), but also apparently [discouraged](https://github.com/w3ctag/design-principles/issues/463))
* A [`Blob`](https://www.w3.org/TR/FileAPI/#dfn-Blob), which has a `text()` and `bytes()` methods (thanks to Joshua Bell for bringing up this suggestion!).
* `object` if everything can be `JSON.parse()`-able

It is not clear to me what are the trade-offs between these options (mostly ergonomics? or are there security trade-offs here?) nor what the requirements are (e.g. do we need to support passing back binary or non-JSON response's data?), so this issue here is intended to try to collect requirements and help us figure out what's best to use.

@marcoscaceres FYI

### PR DESCRIPTION
**Pull request by samuelgoto**
Closes #119

The following tasks have been completed:

- [ ] Modified Web platform tests (link)

Implementation commitment:

- [ ] [WebKit](https://bugs.webkit.org/show_bug.cgi?id=276651)
- [ ] [Chromium](https://g-issues.chromium.org/issues/357100947) 
- [ ] Gecko (link to issue)

Documentation and checks

- [ ] Affects privacy
- [ ] Affects security
- [ ] Pinged MDN
- [ ] Updated Explainer

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/digital-credentials/pull/141.html" title="Last updated on Aug 2, 2024, 5:53 PM UTC (1fea129)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/digital-credentials/141/69a62f2...1fea129.html" title="Last updated on Aug 2, 2024, 5:53 PM UTC (1fea129)">Diff</a>

### CODE REVIEW

**Comment by samuelgoto** [comment]
Before I complete the PR pre-requisites, does this match more or less what we agreed upon in #119 ?

**Comment by marcoscaceres** [comment]
Didn't we also want get a resolution on #95 ?

**Comment by samuelgoto** [comment]
> Didn't we also want get a resolution on https://github.com/WICG/digital-credentials/issues/95 ?

Yes, but that's largely independent of #119 ?

**Comment by marcoscaceres** [comment]
WebKit tracking bug https://bugs.webkit.org/show_bug.cgi?id=276651 

I'll update WebKit hopefully tomorrow.

**Comment by samuelgoto** [comment]
> WebKit tracking bug https://bugs.webkit.org/show_bug.cgi?id=276651

Done, added for chromium too.

**Comment by marcoscaceres** [comment]
@timcappalli, can you also confirm this is correct. Sorry, I'm still a bit confused about where https://github.com/WICG/digital-credentials/issues/95 comes into play and if it has any relationship to this. 

If it has no impact, then please merge this 🙏

**Review by timcappalli — APPROVED** [review]

**Pull request merged**
