### PR TITLE
Drop navigator.identity namespace

### PR DESCRIPTION
**Pull request by marcoscaceres**
Closes #???

The following tasks have been completed:

- [x] [Modified Web platform tests](https://github.com/web-platform-tests/wpt/pull/48117)

Implementation commitment:

- [ ] [WebKit](https://bugs.webkit.org/show_bug.cgi?id=279159)
- [ ] [Chromium](https://g-issues.chromium.org/issues/364957810)
- [ ] Gecko (link to issue)

Documentation and checks

- [ ] Affects privacy
- [ ] Affects security
- [ ] Pinged MDN
- [ ] Updated Explainer

***
<a href="https://pr-preview.s3.amazonaws.com/WICG/digital-credentials/pull/164.html" title="Last updated on Sep 12, 2024, 9:53 AM UTC (e5bd41d)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/WICG/digital-credentials/164/5c07f1f...e5bd41d.html" title="Last updated on Sep 12, 2024, 9:53 AM UTC (e5bd41d)">Diff</a>

### CODE REVIEW

**Review by samuelgoto — APPROVED** [review]
LGTM

**Review by timcappalli — APPROVED** [review]

**Comment by marcoscaceres** [comment]
Filed https://bugs.webkit.org/show_bug.cgi?id=279159 for WebKit... I'll update the tests etc.

**Review by bvandersloot-mozilla — APPROVED** [review]
With the changes to CredMan disallowing `digital` being mixed with other credential types, this is okay.

**Comment by samuelgoto** [comment]
> Filed https://bugs.webkit.org/show_bug.cgi?id=279159 for WebKit... I'll update the tests etc.

Added chromium implementation bug too.

**Comment by marcoscaceres** [comment]
Updates to the test suite:
https://github.com/web-platform-tests/wpt/pull/48117

I need to check these are correct against an engine still, but it's a start. We need to check for redundant tests.

**Comment by samuelgoto** [comment]
> Added chromium implementation bug too.

FWIW, this is already implemented in Chrome Canaries as of last week:

https://g-issues.chromium.org/issues/364957810?pli=1&authuser=0

**Comment by marcoscaceres** [comment]
Great, will try to get WebKit updated soon!

**Pull request merged**
